### ISSUE TITLE
Fix lesson material link

### ISSUE THREAD

**Issue by svenvanderburg** [esciencecenter-digital-skills/template-docs-coordination#4]
The link to the lesson material in the post-workshop email in the communication document template is broken.

**Comment by bvreede** [comment]
Fixed! Without a PR, but with commits [#3a116ae](https://github.com/esciencecenter-digital-skills/template-docs-coordination/commit/3a116ae81ddae60d2cd6f044942fb94c3a74d370) and [#14a5586](https://github.com/esciencecenter-digital-skills/template-docs-coordination/commit/14a5586a374a336e03227c3f016339151b136aef)
