### ISSUE TITLE
Move issues and archive this repository

### ISSUE THREAD

**Issue by bvreede** [esciencecenter-digital-skills/template-docs-coordination#9]
A [PR in the training infrastructure package](https://github.com/esciencecenter-digital-skills/training-infrastructure/pull/56) moves these documents to the package itself. If this gets merged, this repository should be archived and the issues moved to the training infrastructure repo.

**Comment by svenvanderburg** [comment]
This is closed: https://github.com/esciencecenter-digital-skills/training-infrastructure/pull/56 we keep separate repos
